name: Update Profiles on macOS

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 ? * MON,THU "

jobs:
  update-profiles:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x
          architecture: x64

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v3
        with:
          path: "auto_getter/requirements.txt"
          update-pip: "true"
          update-setuptools: "true"
          update-wheel: "true"

      - name: Run Scripts
        run: |
          chmod a+x ./auto_getter/subconverter/darwin64/subconverter
          chmod -R 777 ./auto_getter/subconverter/darwin64/*
          pip3 install beautifulsoup4
          bash ./run.sh

      - name: Add Commit
        run: |
          china_date=$(TZ='Asia/Shanghai' date +%Y-%m-%d" "%H:%M:%S)
          message="更新（代理配置）: \`${china_date}\` 更新。"
          git config --global user.email "<>"
          git config --global user.name "GitHub Actions Bot"
          git add .
          git commit -m "${message}"
          git pull --rebase

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACCESS_TOKEN  }}
